[package]
name = "mc-test-vectors-account-keys"
version = "1.0.1-pre1"
authors = ["MobileCoin"]
edition = "2018"

[dependencies]
mc-test-vectors-definitions = { path = "../definitions" }

[build-dependencies]
mc-account-keys = { path = "../../account-keys" }
mc-test-vectors-definitions = { path = "../definitions" }
mc-util-test-vector = { path = "../../util/test-vector" }
