[package]
name = "mc-crypto-x509-test-vectors"
version = "1.0.0"
authors = ["MobileCoin"]
edition = "2018"
description = "Utilities for generating certificates and chains for unit tests"
readme = "README.md"

[build-dependencies]
cargo-emit = "0.1.1"
mc-util-build-script = { path = "../../../util/build/script" }

[dependencies]
mc-crypto-keys = { path = "../../keys" }

pem = "0.8"
x509-signature = "0.5"
