[package]
name = "mc-fog-sig"
version = "1.0.0"
authors = ["MobileCoin"]
edition = "2018"
description = "Create and verify fog authority and report signatures"

[dependencies]
mc-crypto-keys = { path = "../../crypto/keys" }

displaydoc = { version = "0.1.7", default-features = false }
pem = "0.8"
signature = { version = "1.2.2" }
x509-signature = "0.5"
